trigger:
- none

variables:
  env: $(environment)
  project: $(organizationId)
  pipeline: $(pipelineBuild)
  connection: 'cloud-subscription'
  functionName: $(azFunctionName)
  vmImage: 'ubuntu-latest'

stages:
- stage: Deploy
  jobs:
  - deployment: Deployment
    displayName: 'Agent Job Deploy'
    pool:
      vmImage: '$(vmImage)'
    environment: '$(env)'    
    strategy:
      runOnce:
        deploy:
          steps:          
          - task: DownloadBuildArtifacts@1
            displayName: 'Download .zip build artifact'
            inputs:
              buildType: 'specific'
              project: '$(project)'
              pipeline: '$(pipeline)'
              buildVersionToDownload: 'latest'
              downloadType: 'specific'
              downloadPath: '$(System.ArtifactsDirectory)'
          - task: AzureFunctionApp@1
            displayName: 'Azure Function App Deploy'
            inputs:
              azureSubscription: '$(connection)'
              appType: 'functionAppLinux'
              appName: '$(functionName)'
              package: '$(System.ArtifactsDirectory)/drop/*.zip'