trigger:
- none

variables:
  env: $(environment)
  project: $(organizationId)
  pipeline: $(pipelineBuild)
  azConnection: $(connection)
  azFunctionName: $(functionName)

stages:
- stage: Deploy
  jobs:
  - deployment: Deployment
    displayName: 'Agent Job Deploy'
    pool:
      vmImage: ubuntu-latest
    environment: '$(env)'
    variables:
      conn: '$(azConnection)'
    strategy:
      runOnce:
        deploy:
          steps:          
          - task: DownloadBuildArtifacts@1
            inputs:
              buildType: 'specific'
              project: '$(project)'
              pipeline: '$(pipeline)'
              buildVersionToDownload: 'latest'
              downloadType: 'specific'
              downloadPath: '$(System.ArtifactsDirectory)'
          - task: AzureFunctionApp@1
            displayName: 'Azure Function App Deploy'
            inputs:
              azureSubscription: '$(conn)'
              appType: 'functionAppLinux'
              appName: '$(azFunctionName)'
              package: '$(System.ArtifactsDirectory)/drop/*.zip'