trigger:
- none

variables:
  projectCI: '78da80bb-c644-48e5-b341-2a1ea25a6062'
  pipelineCI: 'cinematic-urm-dev-CI'
  azConnection: 'azure-subscription'
  azFunctionName: 'func-eastus2-dev-cinematic-urm' 

stages:
- stage: Deploy
  jobs:
  - deployment: Deployment
    displayName: 'Agent Job Deploy'
    pool:
      vmImage: ubuntu-latest
    environment: '$(pipelineCI)'
    strategy:
      runOnce:
        deploy:
          steps:          
          - task: DownloadBuildArtifacts@1
            inputs:
              buildType: 'specific'
              project: '$(projectCI)'
              pipeline: '$(pipelineCI)'
              buildVersionToDownload: 'latest'
              downloadType: 'specific'
              downloadPath: '$(System.ArtifactsDirectory)'
          - task: AzureFunctionApp@1
            displayName: 'Azure Function App Deploy'
            inputs:
              azureSubscription: $(azConnection)
              appType: 'functionAppLinux'
              appName: '$(azFunctionName)'
              package: '$(System.ArtifactsDirectory)/drop/*.zip'